### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/ReportSystem-Nukkit#1]
LOG: 12:10:33 [FATAL] "cn.nukkit.event.player.PlayerFormRespondedEvent" 이벤트를 "ReportSystem v1.0-SNAPSHOT"에 전달할 수 없습니다: net.llamadevelopment.reportsystem.listeners.FormListener에서의 null
12:10:33 [ERROR] Throwing                                                                                        cn.nukkit.utils.EventException: null                                                                                     at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]                 at cn.nukkit.Player.handleDataPacket(Player.java:2609) ~[nukkit-1.0-SNAPSHOT.jar:?]                              at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_232]                                                at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]                        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2092) [nukkit-1.0-SNAPSHOT.jar:?]                               at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1124) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:880) [nukkit-1.0-SNAPSHOT.jar:?]                                           at cn.nukkit.Server.<init>(Server.java:565) [nukkit-1.0-SNAPSHOT.jar:?]                                          at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at net.llamadevelopment.reportsystem.listeners.FormListener.on(FormListener.java:77) ~[?:?]                      at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]                                           at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]        ... 16 more

Problem: Error but not crash. Could you fix it please? 😢

**Comment by SchdowNVIDIA** [comment]
How can we reproduce the error? What have you done to get this error?

**Comment by good777LUCKY** [comment]
I have no problem with GUI and commands but it makes this errors sometimes. What can I do for it?

**Comment by SchdowNVIDIA** [comment]
Okay, we will look into that as soon as we can.

**Comment by Mundschutziii** [comment]
Hi. Do you use MongoDB or YAML?

**Comment by good777LUCKY** [comment]
I use YAML.

**Comment by Mundschutziii** [comment]
Tomorrow or the day after tomorrow you can download the new version on Nukkit. The error should be fixed then. Thanks for your report.
